export const CART_ADD_ITEMS = 'CART_ADD_ITEMS'
export const CART_REMOVE_ITEMS = 'CART_REMOVE_ITEMS'

// export const CART_LIST_FAIL = 'CART_LIST_FAIL'

// export const CART_DETAILS_REQUEST = 'CART_DETAILS_REQUEST'
// export const CART_DETAILS_SUCCESS = 'CART_DETAILS_SUCCESS'
// export const CART_DETAILS_FAIL = 'CART_DETAILS_FAIL'
