export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const PRODUCT_CREATE_REVIEWS_REQUEST = 'PRODUCT_CREATE_REVIEWS_REQUEST'
export const PRODUCT_CREATE_REVIEWS_SUCCESS = 'PRODUCT_CREATE_REVIEWS_SUCCESS'
export const PRODUCT_CREATE_REVIEWS_FAIL = 'PRODUCT_CREATE_REVIEWS_FAIL'
export const PRODUCT_CREATE_REVIEWS_RESET = 'PRODUCT_CREATE_REVIEWS_RESTL'
